
-- Users table
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(64) NOT NULL,
    last_name VARCHAR(64) NOT NULL,
    username VARCHAR(64) NOT NULL UNIQUE,
    email VARCHAR(120) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

-- Products table
DROP TABLE IF EXISTS `products`;
CREATE TABLE `products` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    item_description TEXT NULL,
    item_features TEXT NULL,
    feature_list TEXT NULL,
    detail_description TEXT NULL,
    sizes TEXT NULL,
    images TEXT NULL,
    price DECIMAL(10,2) NOT NULL,
    category VARCHAR(50) NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    status BOOLEAN DEFAULT FALSE,
    `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

-- Orders table
DROP TABLE IF EXISTS `orders`;
CREATE TABLE `orders` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

-- Contacts table
DROP TABLE IF EXISTS `contacts`;
CREATE TABLE `contacts` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    name VARCHAR(64) NOT NULL,
    message TEXT NOT NULL,
    phone VARCHAR(64) NOT NULL,
    email VARCHAR(120) NOT NULL,
    `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);

-- Subscribe table
DROP TABLE IF EXISTS `subscribe`;
CREATE TABLE `subscribe`  (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    email VARCHAR(120) NOT NULL,
    `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
    `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
);


INSERT INTO products (id, name, description, item_description, item_features, feature_list, detail_description, sizes, images, price, category, image_url, status, created_at, updated_at) VALUES

(1, 'SKOK 25/55 lbs Pair or Single Adjustable Dumbbells Set', 'SKOK 25/55 lbs Pair or Single Adjustable Dumbbells Set, Adjustable Weights Dumbbells Set for Men and Women with Anti-Slip Fast Adjust Weight by Turning Handle,Black Dumbbell with Tray', "🥇【High Quality & Advanced Technology】Dumbbell's weight plate covered with frosted powder coating, which make it hardly abrasion and don't have foul smell. Using with dumbbell tray, enjoy the smoothly training process. Durable handle combine with anti-slip texture, which would not rusty and provide more safty.
🥇【New Structural Design】Exclusive design of adjustment countweight plate, simply adjust by holding the handleaccording to the weight you need, turn the pointer to the corresponding number to adjust. The latest design locks the dumbbells with 8 locking, which ensure the dumbell set are fastened stably and tightly to ensure your safety.
🥇【Home Fitness Necessity】SKOK adjustable dumbbell supports diverse strength training by changing different weights. Adjustment weights from 11lb to 55lb, even fitness beginners are very easy to use. It is a great choice for modify muscle lines and strong muscle fibers.
🥇【Save Money & Space】It is great for your upper body workouts, which helps tone and sculpt your arms, shoulders and also strengthen your muscles. The dumbbell also come with a tray for secure storage of your units, without devoting too much floor space, and keep your home gym well organized.", NULL, NULL, NULL, NULL, NULL, 930.99, 'Fitness', '/public/images/products/fitness/img1.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03'),
(2, 'Adjustable Weights Dumbbells Set', 'Adjustable Weights Dumbbells Set, Non-Rolling Adjustable Dumbbell Set, Free Weights Dumbbells Set Hexagon, Weights Set for Home Gym, 20 Lbs', "UPGRADE STRUCTURE DESIGN - The weight plate of the TOTOZAKUL upgrade adjustable dumbbells set adopts an octagonal design, which prevents rolling, is safe and stable, and is easy to store.
3 MODES - TOTOZAKUL adjustable dumbbell set, with 3 modes of use: dumbbell, barbell and push-ups. Bring dumbbells to your home，Build your home gym.Get started on your fitness journey with a dumbbell workout!
WEIGHT PACKAGE LIST - 80 lbs fitness dumbbells include: 8 × 6.6lbs weight plates, 4 x 5.5lbs weight plates,4 × 2.75lbs weight plates,4x dumbbell nuts,1x connertor and 2x dumbbell bar. You can choose different weights according to your own preferences to meet the intensity needs of you and your family at different stages of exercise.
THE BEST HOME FITNESS EQUIPMENT - 3-in-1 mode, you can carry out a variety of balance strength training to help exercise biceps brachii, leg and abdominal muscles; It can also help maintain low blood fat and increase oxygen intake to obtain a healthy body.
UPGRADED MATERIAL - Our weight plates are filled with iron sand and wrapped with high-grade PE materials. Prevent damage to the floor and rust. The thickened foam connecting rod conforms to the ergonomic design, reduces the pressure on the shoulder, tobengda and avoids sports injuries.
EASY TO ASSEMBLE AND STORE - Depending on your and your family's exercise needs, you can easily assemble the weight you want. For the exercisers with small space, they can easily disassemble it after use and put it under the table without taking up space.", NULL, NULL, NULL, NULL, NULL, 130.99, 'Fitness', '/public/images/products/fitness/img2.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03'),
(3, 'Basics Neoprene Dumbbell', 'Amazon Basics Neoprene Dumbbell Hand Weights', "3 pound dumbbell (set of 2) for exercise and strength training
Neoprene texture in Purple offers long lasting durability
Hexagon shaped ends prevent dumbbells from rolling away and offer stay-in-place storage
Nonslip grip promotes a comfortable, secure hold
Available in multiple sizes to mix and match for specific workout needs and to expand on over time
Printed weight number on each end cap and color coded for quick identification", NULL, NULL, NULL, NULL, NULL, 830.99, 'Fitness', '/public/images/products/fitness/img3.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03'),
(4, 'Adjustable Weights Dumbbells Set', 'Adjustable Weights Dumbbells Set, Non-Rolling Adjustable Dumbbell Set, Free Weights Dumbbells Set Hexagon, Weights Set for Home Gym, 20 Lbs', "UPGRADE STRUCTURE DESIGN - The weight plate of the TOTOZAKUL upgrade adjustable dumbbells set adopts an octagonal design, which prevents rolling, is safe and stable, and is easy to store.
3 MODES - TOTOZAKUL adjustable dumbbell set, with 3 modes of use: dumbbell, barbell and push-ups. Bring dumbbells to your home，Build your home gym.Get started on your fitness journey with a dumbbell workout!
WEIGHT PACKAGE LIST - 80 lbs fitness dumbbells include: 8 × 6.6lbs weight plates, 4 x 5.5lbs weight plates,4 × 2.75lbs weight plates,4x dumbbell nuts,1x connertor and 2x dumbbell bar. You can choose different weights according to your own preferences to meet the intensity needs of you and your family at different stages of exercise.
THE BEST HOME FITNESS EQUIPMENT - 3-in-1 mode, you can carry out a variety of balance strength training to help exercise biceps brachii, leg and abdominal muscles; It can also help maintain low blood fat and increase oxygen intake to obtain a healthy body.
UPGRADED MATERIAL - Our weight plates are filled with iron sand and wrapped with high-grade PE materials. Prevent damage to the floor and rust. The thickened foam connecting rod conforms to the ergonomic design, reduces the pressure on the shoulder, tobengda and avoids sports injuries.
EASY TO ASSEMBLE AND STORE - Depending on your and your family's exercise needs, you can easily assemble the weight you want. For the exercisers with small space, they can easily disassemble it after use and put it under the table without taking up space.", NULL, NULL, NULL, NULL, NULL, 730.99, 'Fitness', '/public/images/products/fitness/img4.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03'),
(5, 'Basics Neoprene Dumbbell', 'Amazon Basics Neoprene Dumbbell Hand Weights', "3 pound dumbbell (set of 2) for exercise and strength training
Neoprene texture in Purple offers long lasting durability
Hexagon shaped ends prevent dumbbells from rolling away and offer stay-in-place storage
Nonslip grip promotes a comfortable, secure hold
Available in multiple sizes to mix and match for specific workout needs and to expand on over time
Printed weight number on each end cap and color coded for quick identification", NULL, NULL, NULL, NULL, NULL, 430.99, 'Fitness', '/public/images/products/fitness/img5.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03'),
(6, 'VIVITORY Dumbbell Set', 'VIVITORY Dumbbell Set - Adjustable Weights, Free Weights with Connector, Non-Rolling, Hexagon, Cement Mixture - 44 to 66 Lbs', "Flexible & Customizable: The Vivitory adjustable dumbbell set offers adjustable weights that can go up to 66 pounds, making it a perfect choice for a weight set for home workout. It comes with quality connecting rod, handles, screw nuts, and weight plates, giving you a wide range of weight options. You can easily convert it from dumbbell to barbell for a variety of exercises, and it's suitable for fitness novices and professionals alike
Durable & Sturdy Design: Vivitory home dumbbell set features a hexagonal design that prevents scrolling and ensures easy storage. Made with polyethylene and EVA resin, with a cement mixture, it is solid and sturdy, ensuring that there is no damage to the floor. The connecting rod is foam-covered to reduce neck compression and relieve fatigue. The non-slip rubber-coated handle provides a firm grip, making it the perfect home weight set
Multipurpose Fitness Equipment: The Vivitory dumbbell set with adjustable weights is not only a dumbbell and barbell but also a push-up board, grip, and back training device, making it a perfect choice for a home gym weight set for diverse muscle training. It is easy to disassemble and assemble, and it saves you money on other equipment
Healthy & Fitness-Focused: This free weight dumbbell set is ideal for everyone who loves sports and wants to increase their strength, burn fat, and shape their bodies. It is a safer and more stable option than other equipment, making it suitable for fitness novices and the public. Vivitory weight sets for home gym are the perfect choice for a healthy lifestyle
Why choose VIVITORY: We stand behind our products and have confidence that you will be 100% satisfied with your purchase. Our 24/7 customer service is always available to address any concern you may have. With our weight sets dumbbells, you can be confident that you are making a wise investment in your health and fitness journey. Click 'add to cart' now and start your journey to a healthier you", NULL, NULL, NULL, NULL, NULL, 530.99, 'Fitness', '/public/images/products/fitness/img6.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03'),
(7, 'Basics Neoprene Dumbbell', 'Amazon Basics Neoprene Dumbbell Hand Weights', "3 pound dumbbell (set of 2) for exercise and strength training
Neoprene texture in Purple offers long lasting durability
Hexagon shaped ends prevent dumbbells from rolling away and offer stay-in-place storage
Nonslip grip promotes a comfortable, secure hold
Available in multiple sizes to mix and match for specific workout needs and to expand on over time
Printed weight number on each end cap and color coded for quick identification", NULL, NULL, NULL, NULL, NULL, 330.99, 'Fitness', '/public/images/products/fitness/img7.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03'),
(8, 'Adjustable Weights Dumbbells Set', 'Adjustable Weights Dumbbells Set, Non-Rolling Adjustable Dumbbell Set, Free Weights Dumbbells Set Hexagon, Weights Set for Home Gym, 20 Lbs', "UPGRADE STRUCTURE DESIGN - The weight plate of the TOTOZAKUL upgrade adjustable dumbbells set adopts an octagonal design, which prevents rolling, is safe and stable, and is easy to store.
3 MODES - TOTOZAKUL adjustable dumbbell set, with 3 modes of use: dumbbell, barbell and push-ups. Bring dumbbells to your home，Build your home gym.Get started on your fitness journey with a dumbbell workout!
WEIGHT PACKAGE LIST - 80 lbs fitness dumbbells include: 8 × 6.6lbs weight plates, 4 x 5.5lbs weight plates,4 × 2.75lbs weight plates,4x dumbbell nuts,1x connertor and 2x dumbbell bar. You can choose different weights according to your own preferences to meet the intensity needs of you and your family at different stages of exercise.
THE BEST HOME FITNESS EQUIPMENT - 3-in-1 mode, you can carry out a variety of balance strength training to help exercise biceps brachii, leg and abdominal muscles; It can also help maintain low blood fat and increase oxygen intake to obtain a healthy body.
UPGRADED MATERIAL - Our weight plates are filled with iron sand and wrapped with high-grade PE materials. Prevent damage to the floor and rust. The thickened foam connecting rod conforms to the ergonomic design, reduces the pressure on the shoulder, tobengda and avoids sports injuries.
EASY TO ASSEMBLE AND STORE - Depending on your and your family's exercise needs, you can easily assemble the weight you want. For the exercisers with small space, they can easily disassemble it after use and put it under the table without taking up space.", NULL, NULL, NULL, NULL, NULL, 630.99, 'Fitness', '/public/images/products/fitness/img8.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03'),
(9, 'SKOK 25/55 lbs Pair or Single Adjustable Dumbbells Set', 'SKOK 25/55 lbs Pair or Single Adjustable Dumbbells Set, Adjustable Weights Dumbbells Set for Men and Women with Anti-Slip Fast Adjust Weight by Turning Handle,Black Dumbbell with Tray', "🥇【High Quality & Advanced Technology】Dumbbell's weight plate covered with frosted powder coating, which make it hardly abrasion and don't have foul smell. Using with dumbbell tray, enjoy the smoothly training process. Durable handle combine with anti-slip texture, which would not rusty and provide more safty.
🥇【New Structural Design】Exclusive design of adjustment countweight plate, simply adjust by holding the handleaccording to the weight you need, turn the pointer to the corresponding number to adjust. The latest design locks the dumbbells with 8 locking, which ensure the dumbell set are fastened stably and tightly to ensure your safety.
🥇【Home Fitness Necessity】SKOK adjustable dumbbell supports diverse strength training by changing different weights. Adjustment weights from 11lb to 55lb, even fitness beginners are very easy to use. It is a great choice for modify muscle lines and strong muscle fibers.
🥇【Save Money & Space】It is great for your upper body workouts, which helps tone and sculpt your arms, shoulders and also strengthen your muscles. The dumbbell also come with a tray for secure storage of your units, without devoting too much floor space, and keep your home gym well organized.", NULL, NULL, NULL, NULL, NULL, 630.99, 'Fitness', '/public/images/products/fitness/img9.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03'),
(10, 'Dumbbell Adjustable', 'Yes4All Dumbbell Adjustable - 105lbs', "105LB SET OF 2 DUMBBELLS: Yes4All dumbbells adjustable weight includes TWO 16” x 1” handles, SIXTEEN 5lbs plates, FOUR 2.5lbs plates, FOUR 1.25lbs plates, FOUR collars handles, shipped in two packages; Customize your workout intensity with this 105lb dumbbells set of 2
DURABLE & LONG LASTING CAST IRON: Made with heavy-duty cast iron & protective coating, these adjustable 40lb to 200lb dumbbells set are built to last; Our dumbbells set of 2 prevents rusting and chipping for reliable use
NON-SLIP & COMFORTABLE GRIP: Ergonomic handles of adjustable dumbbells provide stable & non-slip grip even with sweat hand; Firm diamond knurled textured chrome dumbbell handle allows longer workout sessions
SECURED DUMBBELL WITH INCLUDED COLLARS: Enjoy efficient workout session without worrying about looseness; Stay focused on targeting various muscle groups effectively with our adaptable dumbbells - adjustable weight plate set of 2
VERSATILE USE - Use this dumbbell set for a full body workout, including arms, chest, back, core, and legs! You can also use them as an alternative to barbells or kettle bells when performing squats or lunges for added intensity", NULL, NULL, NULL, NULL, NULL, 930.99, 'Fitness', '/public/images/products/fitness/img10.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03'),
(11, 'Basics Neoprene Dumbbell', 'Amazon Basics Neoprene Dumbbell Hand Weights', "3 pound dumbbell (set of 2) for exercise and strength training
Neoprene texture in Purple offers long lasting durability
Hexagon shaped ends prevent dumbbells from rolling away and offer stay-in-place storage
Nonslip grip promotes a comfortable, secure hold
Available in multiple sizes to mix and match for specific workout needs and to expand on over time
Printed weight number on each end cap and color coded for quick identification", NULL, NULL, NULL, NULL, NULL, 530.99, 'Fitness', '/public/images/products/fitness/img11.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03'),


(12, 'OLEVS Men Classic Business Wristwatch', 'OLEVS Men Watch,Big Dial Watches for Men Stainless Steel Watch with Day Waterproof Analog Quartz Watches for Man Classic Business Wristwatch Luxury Luminous Round for Men Rotatable Bezel Watch', "[Precise Chronograph Watches] With design elements from the minutes chronograph,seconds chronograph and calendar window,the OLEVS quartz watch is both fashion and luxury.The watch combines a sleek,business design with classic blue dial and luminous(NOTE: Non-self-illuminating,need to luminate the Watch for 30 Seconds Under the Light or absorb the sunshine)that give the timepiece a refined, professional look.With a 42.5mm case,it's big enough to be visible,but not too big to be uncomfortable.
[Well-designed] A chronograph with a pop of color.Extra striking is the 24 hour purple moon phase,which surprises every glance at the watch.This beautiful eye-catcher unleashes the charm in every man.The bold details enhance the wearer's personality and upgrade both the casual and the business look
[Stainless Steel Watches]A steel strap men's watch is the perfect all-round watch for everyday use and every occasion.Make your wrist a striking appearance.This design is made with care and precision to ensure the best quality and durability.This way you enjoy optimal wearing comfort and you strengthen the good impression people get of you. Free adjustment tool from seller
[Perfect Gifts for Men] Watches come with OLEVS brand box,it is the preferred gift for father,husband,son,brother,boyfriend,friend and more.Suitable for Father's Day,Christmas,New Year,sports,dating,fishing,birthday,graduation ceremony,Souvenir.
[After-Sale Professional Service] We provide 24 months warranty and 30-day money back guarantee.If you have problems during use of the wristwatch,please feel free to contact us,we will provide you professional service.Water resistant to 100 feet (30 m), suitable for daily use.Not suitable for bathing,swimming,diving and other water related work.", NULL, NULL, NULL, NULL, NULL, 130.99, 'Watches', '/public/images/products/watches/img1.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03'),
(13, 'ENOMIR Smart Watch for Women Men with Bluetooth Call', 'ENOMIR Smart Watch for Women Men with Bluetooth Call,Smartwatch with Alexa Built-in,Heart Rate SpO2 Sleep Monitor,5ATM Waterproof,Step Calorie Activity Trackers and Smartwatches for iOS&Android Phones', "Running and 5ATM Waterproof: Achieve your fitness goals with over 100 sports modes(Run, trail run, bike, swim and so on) tailored to your workouts.Running watch for women tracks Calories burned, Step count, Exercise Time, and Distance for a wide range of activities.Plus, Activity trackers and smartwatches are built to withstand water up to 5 ATM, making it your ideal workout partner.
24-Hour Health Automatically Tracker: Prioritize your well-being with sport watches for men women continuous health monitoring. Track your Heart Rate, Blood Oxygen levels, Stress levels, and Sleep patterns(Deep sleep, light sleep, REM analysis) around the clock.Take charge of your well-being and make informed decisions for a healthier lifestyle.
Wrist Calls and APP Notifications: Stay connected seamlessly with using Smartwatch to make/answer Bluetooth calls and receive SMS and APP messages(Facebook, WhatsApp, Twitter, etc) convenient for your life and will never miss important alert.Note: After connecting Bluetooth, please turn on message and call notification in VeryFit APP.Note: After connecting Bluetooth, please turn on message and call notification in VeryFit APP.(Can not send messages or text back,Bluetooth distance is 10m).
Alexa Built-In and Life Assistant: Enjoy the convenience of Alexa, your virtual assistant, right on your wrist. Ask questions, set reminders, control smart devices, and more, all with your fitness tracker.There are also some life features such as:alarm clock, stopwatch, camera and music control, sedentary reminder, breathing training, menstrual period record
7 Days Using:Enjoy extended usage with up to 7 days of battery life on a single charge,running-gps-unit allowing you to focus on your activities without worrying about frequent charging.We stand by the quality and durability of fitness watch, ensuring your peace of mind with your purchase.", NULL, NULL, NULL, NULL, NULL, 130.99, 'Watches', '/public/images/products/watches/img2.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03'),
(14, 'ENOMIR Smart Watch for Women Men with Bluetooth Call', 'ENOMIR Smart Watch for Women Men with Bluetooth Call,Smartwatch with Alexa Built-in,Heart Rate SpO2 Sleep Monitor,5ATM Waterproof,Step Calorie Activity Trackers and Smartwatches for iOS&Android Phones', "Running and 5ATM Waterproof: Achieve your fitness goals with over 100 sports modes(Run, trail run, bike, swim and so on) tailored to your workouts.Running watch for women tracks Calories burned, Step count, Exercise Time, and Distance for a wide range of activities.Plus, Activity trackers and smartwatches are built to withstand water up to 5 ATM, making it your ideal workout partner.
24-Hour Health Automatically Tracker: Prioritize your well-being with sport watches for men women continuous health monitoring. Track your Heart Rate, Blood Oxygen levels, Stress levels, and Sleep patterns(Deep sleep, light sleep, REM analysis) around the clock.Take charge of your well-being and make informed decisions for a healthier lifestyle.
Wrist Calls and APP Notifications: Stay connected seamlessly with using Smartwatch to make/answer Bluetooth calls and receive SMS and APP messages(Facebook, WhatsApp, Twitter, etc) convenient for your life and will never miss important alert.Note: After connecting Bluetooth, please turn on message and call notification in VeryFit APP.Note: After connecting Bluetooth, please turn on message and call notification in VeryFit APP.(Can not send messages or text back,Bluetooth distance is 10m).
Alexa Built-In and Life Assistant: Enjoy the convenience of Alexa, your virtual assistant, right on your wrist. Ask questions, set reminders, control smart devices, and more, all with your fitness tracker.There are also some life features such as:alarm clock, stopwatch, camera and music control, sedentary reminder, breathing training, menstrual period record
7 Days Using:Enjoy extended usage with up to 7 days of battery life on a single charge,running-gps-unit allowing you to focus on your activities without worrying about frequent charging.We stand by the quality and durability of fitness watch, ensuring your peace of mind with your purchase.", NULL, NULL, NULL, NULL, NULL, 730.99, 'Watches', '/public/images/products/watches/img3.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03'),
(15, 'OLEVS Men Classic Business Wristwatch', 'OLEVS Men Watch,Big Dial Watches for Men Stainless Steel Watch with Day Waterproof Analog Quartz Watches for Man Classic Business Wristwatch Luxury Luminous Round for Men Rotatable Bezel Watch', "[Precise Chronograph Watches] With design elements from the minutes chronograph,seconds chronograph and calendar window,the OLEVS quartz watch is both fashion and luxury.The watch combines a sleek,business design with classic blu and luminous(NOTE: Non-self-illuminating,need to luminate the Watch for 30 Seconds Under the Light or absorb the sunshine)that give the timepiece a refined, professional look.With a 42.5mm case,it's big enough to be visible,but not too big to be uncomfortable.
[Well-designed] A chronograph with a pop of color.Extra striking is the 24 hour purple moon phase,which surprises every glance at the watch.This beautiful eye-catcher unleashes the charm in every man.The bold details enhance the wearer's personality and upgrade both the casual and the business look
[Stainless Steel Watches]A steel strap men's watch is the perfect all-round watch for everyday use and every occasion.Make your wrist a striking appearance.This design is made with care and precision to ensure the best quality and durability.This way you enjoy optimal wearing comfort and you strengthen the good impression people get of you. Free adjustment tool from seller
[Perfect Gifts for Men] Watches come with OLEVS brand box,it is the preferred gift for father,husband,son,brother,boyfriend,friend and more.Suitable for Father's Day,Christmas,New Year,sports,dating,fishing,birthday,graduation ceremony,Souvenir.
[After-Sale Professional Service] We provide 24 months warranty and 30-day money back guarantee.If you have problems during use of the wristwatch,please feel free to contact us,we will provide you professional service.Water resistant to 100 feet (30 m), suitable for daily use.Not suitable for bathing,swimming,diving and other water related work.", NULL, NULL, NULL, NULL, NULL, 530.99, 'Watches', '/public/images/products/watches/img4.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03'),
(16, 'ENOMIR Smart Watch for Women Men with Bluetooth Call', 'ENOMIR Smart Watch for Women Men with Bluetooth Call,Smartwatch with Alexa Built-in,Heart Rate SpO2 Sleep Monitor,5ATM Waterproof,Step Calorie Activity Trackers and Smartwatches for iOS&Android Phones', "Running and 5ATM Waterproof: Achieve your fitness goals with over 100 sports modes(Run, trail run, bike, swim and so on) tailored to your workouts.Running watch for women tracks Calories burned, Step count, Exercise Time, and Distance for a wide range of activities.Plus, Activity trackers and smartwatches are built to withstand water up to 5 ATM, making it your ideal workout partner.
24-Hour Health Automatically Tracker: Prioritize your well-being with sport watches for men women continuous health monitoring. Track your Heart Rate, Blood Oxygen levels, Stress levels, and Sleep patterns(Deep sleep, light sleep, REM analysis) around the clock.Take charge of your well-being and make informed decisions for a healthier lifestyle.
Wrist Calls and APP Notifications: Stay connected seamlessly with using Smartwatch to make/answer Bluetooth calls and receive SMS and APP messages(Facebook, WhatsApp, Twitter, etc) convenient for your life and will never miss important alert.Note: After connecting Bluetooth, please turn on message and call notification in VeryFit APP.Note: After connecting Bluetooth, please turn on message and call notification in VeryFit APP.(Can not send messages or text back,Bluetooth distance is 10m).
Alexa Built-In and Life Assistant: Enjoy the convenience of Alexa, your virtual assistant, right on your wrist. Ask questions, set reminders, control smart devices, and more, all with your fitness tracker.There are also some life features such as:alarm clock, stopwatch, camera and music control, sedentary reminder, breathing training, menstrual period record
7 Days Using:Enjoy extended usage with up to 7 days of battery life on a single charge,running-gps-unit allowing you to focus on your activities without worrying about frequent charging.We stand by the quality and durability of fitness watch, ensuring your peace of mind with your purchase.", NULL, NULL, NULL, NULL, NULL, 320.99, 'Watches', '/public/images/products/watches/img5.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03'),
(17, 'Fitbit Inspire 3 Health &-Fitness-Tracker', 'Fitbit Inspire 3 Health &-Fitness-Tracker with Stress Management, Workout Intensity, Sleep Tracking, 24/7 Heart Rate and more, Midnight Zen/Black One Size (S & L Bands Included)', "Inspire 3 is the tracker that helps you find your energy, do what you love and feel your best. All you have to do is wear it.Operating temperature: 0° to 40°C
Move more: Daily Readiness Score(1), Active Zone Minutes, all-day activity tracking and 24/7 heart rate, 20+ exercise modes, automatic exercise tracking and reminders to move
Stress less: always-on wellness tracking, daily Stress Management Score, mindfulness sessions, relax breathing sessions, irregular heart rhythm notifications(2), SpO2(3), menstrual health tracking, resting heart rate and high/low heart rate notifications
Sleep better: automatic sleep tracking, personalized Sleep Profile(1), daily detailed Sleep Score, smart wake vibrating alarm, sleep mode
Comfortably connected day and night: calls, texts & smartphone app notifications(4), color touchscreen with customizable clock faces, super lightweight and water resistant to 50 meters, up to 10 day battery life(5)
Includes a 6-month Premium membership complete with personalized insights, advanced analytics and more (New & returning Premium users only. Must activate trial within 60-days of device activation. Content and features may change)", NULL, NULL, NULL, NULL, NULL, 311.99, 'Watches', '/public/images/products/watches/img6.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03'),
(18, 'OLEVS Men Classic Business Wristwatch', 'OLEVS Men Watch,Big Dial Watches for Men Stainless Steel Watch with Day Waterproof Analog Quartz Watches for Man Classic Business Wristwatch Luxury Luminous Round for Men Rotatable Bezel Watch', "[Precise Chronograph Watches] With design elements from the minutes chronograph,seconds chronograph and calendar window,the OLEVS quartz watch is both fashion and luxury.The watch combines a sleek,business design with classic blue dial and luminous(NOTE: Non-self-illuminating,need to luminate the Watch for 30 Seconds Under the Light or absorb the sunshine)that give the timepiece a refined, professional look.With a 42.5mm case,it's big enough to be visible,but not too big to be uncomfortable.
[Well-designed] A chronograph with a pop of color.Extra striking is the 24 hour purple moon phase,which surprises every glance at the watch.This beautiful eye-catcher unleashes the charm in every man.The bold details enhance the wearer's personality and upgrade both the casual and the business look
[Stainless Steel Watches]A steel strap men's watch is the perfect all-round watch for everyday use and every occasion.Make your wrist a striking appearance.This design is made with care and precision to ensure the best quality and durability.This way you enjoy optimal wearing comfort and you strengthen the good impression people get of you. Free adjustment tool from seller
[Perfect Gifts for Men] Watches come with OLEVS brand box,it is the preferred gift for father,husband,son,brother,boyfriend,friend and more.Suitable for Father's Day,Christmas,New Year,sports,dating,fishing,birthday,graduation ceremony,Souvenir.
[After-Sale Professional Service] We provide 24 months warranty and 30-day money back guarantee.If you have problems during use of the wristwatch,please feel free to contact us,we will provide you professional service.Water resistant to 100 feet (30 m), suitable for daily use.Not suitable for bathing,swimming,diving and other water related work.", NULL, NULL, NULL, NULL, NULL, 90.99, 'Watches', '/public/images/products/watches/img7.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03'),
(19, 'Fitbit Inspire 3 Health &-Fitness-Tracker', 'Fitbit Inspire 3 Health &-Fitness-Tracker with Stress Management, Workout Intensity, Sleep Tracking, 24/7 Heart Rate and more, Midnight Zen/Black One Size (S & L Bands Included)', "Inspire 3 is the tracker that helps you find your energy, do what you love and feel your best. All you have to do is wear it.Operating temperature: 0° to 40°C
Move more: Daily Readiness Score(1), Active Zone Minutes, all-day activity tracking and 24/7 heart rate, 20+ exercise modes, automatic exercise tracking and reminders to move
Stress less: always-on wellness tracking, daily Stress Management Score, mindfulness sessions, relax breathing sessions, irregular heart rhythm notifications(2), SpO2(3), menstrual health tracking, resting heart rate and high/low heart rate notifications
Sleep better: automatic sleep tracking, personalized Sleep Profile(1), daily detailed Sleep Score, smart wake vibrating alarm, sleep mode
Comfortably connected day and night: calls, texts & smartphone app notifications(4), color touchscreen with customizable clock faces, super lightweight and water resistant to 50 meters, up to 10 day battery life(5)
Includes a 6-month Premium membership complete with personalized insights, advanced analytics and more (New & returning Premium users only. Must activate trial within 60-days of device activation. Content and features may change)", NULL, NULL, NULL, NULL, NULL, 310.99, 'Watches', '/public/images/products/watches/img8.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03'),
(20, 'ENOMIR Smart Watch for Women Men with Bluetooth Call', 'ENOMIR Smart Watch for Women Men with Bluetooth Call,Smartwatch with Alexa Built-in,Heart Rate SpO2 Sleep Monitor,5ATM Waterproof,Step Calorie Activity Trackers and Smartwatches for iOS&Android Phones', "Running and 5ATM Waterproof: Achieve your fitness goals with over 100 sports modes(Run, trail run, bike, swim and so on) tailored to your workouts.Running watch for women tracks Calories burned, Step count, Exercise Time, and Distance for a wide range of activities.Plus, Activity trackers and smartwatches are built to withstand water up to 5 ATM, making it your ideal workout partner.
24-Hour Health Automatically Tracker: Prioritize your well-being with sport watches for men women continuous health monitoring. Track your Heart Rate, Blood Oxygen levels, Stress levels, and Sleep patterns(Deep sleep, light sleep, REM analysis) around the clock.Take charge of your well-being and make informed decisions for a healthier lifestyle.
Wrist Calls and APP Notifications: Stay connected seamlessly with using Smartwatch to make/answer Bluetooth calls and receive SMS and APP messages(Facebook, WhatsApp, Twitter, etc) convenient for your life and will never miss important alert.Note: After connecting Bluetooth, please turn on message and call notification in VeryFit APP.Note: After connecting Bluetooth, please turn on message and call notification in VeryFit APP.(Can not send messages or text back,Bluetooth distance is 10m).
Alexa Built-In and Life Assistant: Enjoy the convenience of Alexa, your virtual assistant, right on your wrist. Ask questions, set reminders, control smart devices, and more, all with your fitness tracker.There are also some life features such as:alarm clock, stopwatch, camera and music control, sedentary reminder, breathing training, menstrual period record
7 Days Using:Enjoy extended usage with up to 7 days of battery life on a single charge,running-gps-unit allowing you to focus on your activities without worrying about frequent charging.We stand by the quality and durability of fitness watch, ensuring your peace of mind with your purchase.", NULL, NULL, NULL, NULL, NULL, 60.99, 'Watches', '/public/images/products/watches/img9.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03'),
(21, 'OLEVS Men Classic Business Wristwatch', 'OLEVS Men Watch,Big Dial Watches for Men Stainless Steel Watch with Day Waterproof Analog Quartz Watches for Man Classic Business Wristwatch Luxury Luminous Round for Men Rotatable Bezel Watch', "[Precise Chronograph Watches] With design elements from the minutes chronograph,seconds chronograph and calendar window,the OLEVS quartz watch is both fashion and luxury.The watch combines a sleek,business design with classic blue dial and luminous(NOTE: Non-self-illuminating,need to luminate the Watch for 30 Seconds Under the Light or absorb the sunshine)that give the timepiece a refined, professional look.With a 42.5mm case,it's big enough to be visible,but not too big to be uncomfortable.
[Well-designed] A chronograph with a pop of color.Extra striking is the 24 hour purple moon phase,which surprises every glance at the watch.This beautiful eye-catcher unleashes the charm in every man.The bold details enhance the wearer's personality and upgrade both the casual and the business look
[Stainless Steel Watches]A steel strap men's watch is the perfect all-round watch for everyday use and every occasion.Make your wrist a striking appearance.This design is made with care and precision to ensure the best quality and durability.This way you enjoy optimal wearing comfort and you strengthen the good impression people get of you. Free adjustment tool from seller
[Perfect Gifts for Men] Watches come with OLEVS brand box,it is the preferred gift for father,husband,son,brother,boyfriend,friend and more.Suitable for Father's Day,Christmas,New Year,sports,dating,fishing,birthday,graduation ceremony,Souvenir.
[After-Sale Professional Service] We provide 24 months warranty and 30-day money back guarantee.If you have problems during use of the wristwatch,please feel free to contact us,we will provide you professional service.Water resistant to 100 feet (30 m), suitable for daily use.Not suitable for bathing,swimming,diving and other water related work.", NULL, NULL, NULL, NULL, NULL, 130.99, 'Watches', '/public/images/products/watches/img10.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03'),
(22, 'ENOMIR Smart Watch for Women Men with Bluetooth Call', 'ENOMIR Smart Watch for Women Men with Bluetooth Call,Smartwatch with Alexa Built-in,Heart Rate SpO2 Sleep Monitor,5ATM Waterproof,Step Calorie Activity Trackers and Smartwatches for iOS&Android Phones', "Running and 5ATM Waterproof: Achieve your fitness goals with over 100 sports modes(Run, trail run, bike, swim and so on) tailored to your workouts.Running watch for women tracks Calories burned, Step count, Exercise Time, and Distance for a wide range of activities.Plus, Activity trackers and smartwatches are built to withstand water up to 5 ATM, making it your ideal workout partner.
24-Hour Health Automatically Tracker: Prioritize your well-being with sport watches for men women continuous health monitoring. Track your Heart Rate, Blood Oxygen levels, Stress levels, and Sleep patterns(Deep sleep, light sleep, REM analysis) around the clock.Take charge of your well-being and make informed decisions for a healthier lifestyle.
Wrist Calls and APP Notifications: Stay connected seamlessly with using Smartwatch to make/answer Bluetooth calls and receive SMS and APP messages(Facebook, WhatsApp, Twitter, etc) convenient for your life and will never miss important alert.Note: After connecting Bluetooth, please turn on message and call notification in VeryFit APP.Note: After connecting Bluetooth, please turn on message and call notification in VeryFit APP.(Can not send messages or text back,Bluetooth distance is 10m).
Alexa Built-In and Life Assistant: Enjoy the convenience of Alexa, your virtual assistant, right on your wrist. Ask questions, set reminders, control smart devices, and more, all with your fitness tracker.There are also some life features such as:alarm clock, stopwatch, camera and music control, sedentary reminder, breathing training, menstrual period record
7 Days Using:Enjoy extended usage with up to 7 days of battery life on a single charge,running-gps-unit allowing you to focus on your activities without worrying about frequent charging.We stand by the quality and durability of fitness watch, ensuring your peace of mind with your purchase.", NULL, NULL, NULL, NULL, NULL, 80.99, 'Watches', '/public/images/products/watches/img11.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03'),
(23, 'Fitbit Inspire 3 Health &-Fitness-Tracker', 'Fitbit Inspire 3 Health &-Fitness-Tracker with Stress Management, Workout Intensity, Sleep Tracking, 24/7 Heart Rate and more, Midnight Zen/Black One Size (S & L Bands Included)', "Inspire 3 is the tracker that helps you find your energy, do what you love and feel your best. All you have to do is wear it.Operating temperature: 0° to 40°C
Move more: Daily Readiness Score(1), Active Zone Minutes, all-day activity tracking and 24/7 heart rate, 20+ exercise modes, automatic exercise tracking and reminders to move
Stress less: always-on wellness tracking, daily Stress Management Score, mindfulness sessions, relax breathing sessions, irregular heart rhythm notifications(2), SpO2(3), menstrual health tracking, resting heart rate and high/low heart rate notifications
Sleep better: automatic sleep tracking, personalized Sleep Profile(1), daily detailed Sleep Score, smart wake vibrating alarm, sleep mode
Comfortably connected day and night: calls, texts & smartphone app notifications(4), color touchscreen with customizable clock faces, super lightweight and water resistant to 50 meters, up to 10 day battery life(5)
Includes a 6-month Premium membership complete with personalized insights, advanced analytics and more (New & returning Premium users only. Must activate trial within 60-days of device activation. Content and features may change)", NULL, NULL, NULL, NULL, NULL, 40.99, 'Watches', '/public/images/products/watches/img12.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03'),
(24, 'OLEVS Men Classic Business Wristwatch', 'OLEVS Men Watch,Big Dial Watches for Men Stainless Steel Watch with Day Waterproof Analog Quartz Watches for Man Classic Business Wristwatch Luxury Luminous Round for Men Rotatable Bezel Watch', "[Precise Chronograph Watches] With design elements from the minutes chronograph,seconds chronograph and calendar window,the OLEVS quartz watch is both fashion and luxury.The watch combines a sleek,business design with classic blue dial and luminous(NOTE: Non-self-illuminating,need to luminate the Watch for 30 Seconds Under the Light or absorb the sunshine)that give the timepiece a refined, professional look.With a 42.5mm case,it's big enough to be visible,but not too big to be uncomfortable.
[Well-designed] A chronograph with a pop of color.Extra striking is the 24 hour purple moon phase,which surprises every glance at the watch.This beautiful eye-catcher unleashes the charm in every man.The bold details enhance the wearer's personality and upgrade both the casual and the business look
[Stainless Steel Watches]A steel strap men's watch is the perfect all-round watch for everyday use and every occasion.Make your wrist a striking appearance.This design is made with care and precision to ensure the best quality and durability.This way you enjoy optimal wearing comfort and you strengthen the good impression people get of you. Free adjustment tool from seller
[Perfect Gifts for Men] Watches come with OLEVS brand box,it is the preferred gift for father,husband,son,brother,boyfriend,friend and more.Suitable for Father's Day,Christmas,New Year,sports,dating,fishing,birthday,graduation ceremony,Souvenir.
[After-Sale Professional Service] We provide 24 months warranty and 30-day money back guarantee.If you have problems during use of the wristwatch,please feel free to contact us,we will provide you professional service.Water resistant to 100 feet (30 m), suitable for daily use.Not suitable for bathing,swimming,diving and other water related work.", NULL, NULL, NULL, NULL, NULL, 30.99, 'Watches', '/public/images/products/watches/img13.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03'),


(25, '2 Drawer Rolling File Cabinet', 'Bush Furniture Key West 2 Drawer Rolling File Cabinet in Cape Cod Gray Mobile Organization for Home Office Small Under Desk Storage on Wheels', "Versatile Rolling File Cart - This mobile file cabinet measures 16W x 20D x 23H and rolls on casters for easy portability, perfect for both home and office.
2 Drawer File Cabinets for Home Office - Keep important documents organized and secure with this 2 drawer file cabinet that features full-extension ball bearing slides.
Small Office File Cabinets - This small file cabinet fits perfectly in compact office spaces and features a box drawer for organizing personal items.
Sturdy and Secure File Storage - The file drawer holds letter and legal-size documents, so you can keep all of your most important papers in one convenient place.
The Key West Collection - Post leg designs, unique X pattern accents and a weathered finish bring easy-going charm to any living space; Take your personal workspace to the next level with a range of furniture solutions in several attractive finishes.", NULL, NULL, NULL, NULL, NULL, 310.99, 'Furniture', '/public/images/products/furniture/img1.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03'),
(26, 'West Lateral File Cabinet', 'Bush Furniture Key West Lateral File Cabinet, Modern Farmhouse 2 Drawer File Cabinet for Home Office', "MODERN FARMHOUSE STYLE: Drawers with unique X pattern accents, a sturdy post leg design, and your choice of several slightly distressed finish options give this farmhouse filing cabinet a look that works well in homes with casual style. The Key West Collection's easy-going charm is a perfect way to convey a relaxed coastal vibe in any living space.
HOME OFFICE STORAGE: Enjoy a clutter-free workspace with paperwork that's always organized and accessible so you can access important files instantly. Each of the lateral filing cabinet's drawers can hold letter, legal, and A4-size documents weighing up to 50 pounds. Drawers open on smooth full-extension ball bearing slides for an effortless reach to contents.
COORDINATED DESIGN: The height of the 2 Drawer File Cabinet matches that of coordinating Key West Desks (sold separately) for the option to create an extended work surface when placed side-by-side. Take advantage of the extra space to keep your primary desktop clear while any documents you may need stay within arm's reach so you can access them quickly and easily.
FAMILY-FRIENDLY SAFETY: The Lateral File Cabinet's Open Safe Drawers are designed to extend one at a time for maximum stability on both hard and carpeted surfaces. Along with its stable design, the filing cabinet for home office also includes wall attachment hardware for family-friendly safety and stability in any workspace or living space.
COHESIVE LOOK: The Key West Collection offers an array of solutions to enhance your home office and keep the same modern farmhouse style throughout the home. Upgrade your workspace with a matching computer desk and bookcase or outfit your entire home with Key West's coordinating entryway, living room, and bathroom furniture (sold separately).", NULL, NULL, NULL, NULL, NULL, 390.99, 'Furniture', '/public/images/products/furniture/img2.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03'),
(27, '2 Drawer Rolling File Cabinet', 'Bush Furniture Key West 2 Drawer Rolling File Cabinet in Cape Cod Gray Mobile Organization for Home Office Small Under Desk Storage on Wheels', "Versatile Rolling File Cart - This mobile file cabinet measures 16W x 20D x 23H and rolls on casters for easy portability, perfect for both home and office.
2 Drawer File Cabinets for Home Office - Keep important documents organized and secure with this 2 drawer file cabinet that features full-extension ball bearing slides.
Small Office File Cabinets - This small file cabinet fits perfectly in compact office spaces and features a box drawer for organizing personal items.
Sturdy and Secure File Storage - The file drawer holds letter and legal-size documents, so you can keep all of your most important papers in one convenient place.
The Key West Collection - Post leg designs, unique X pattern accents and a weathered finish bring easy-going charm to any living space; Take your personal workspace to the next level with a range of furniture solutions in several attractive finishes.", NULL, NULL, NULL, NULL, NULL, 320.99, 'Furniture', '/public/images/products/furniture/img3.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03'),
(30, 'West Lateral File Cabinet', 'Bush Furniture Key West Lateral File Cabinet, Modern Farmhouse 2 Drawer File Cabinet for Home Office', "MODERN FARMHOUSE STYLE: Drawers with unique X pattern accents, a sturdy post leg design, and your choice of several slightly distressed finish options give this farmhouse filing cabinet a look that works well in homes with casual style. The Key West Collection's easy-going charm is a perfect way to convey a relaxed coastal vibe in any living space.
HOME OFFICE STORAGE: Enjoy a clutter-free workspace with paperwork that's always organized and accessible so you can access important files instantly. Each of the lateral filing cabinet's drawers can hold letter, legal, and A4-size documents weighing up to 50 pounds. Drawers open on smooth full-extension ball bearing slides for an effortless reach to contents.
COORDINATED DESIGN: The height of the 2 Drawer File Cabinet matches that of coordinating Key West Desks (sold separately) for the option to create an extended work surface when placed side-by-side. Take advantage of the extra space to keep your primary desktop clear while any documents you may need stay within arm's reach so you can access them quickly and easily.
FAMILY-FRIENDLY SAFETY: The Lateral File Cabinet's Open Safe Drawers are designed to extend one at a time for maximum stability on both hard and carpeted surfaces. Along with its stable design, the filing cabinet for home office also includes wall attachment hardware for family-friendly safety and stability in any workspace or living space.
COHESIVE LOOK: The Key West Collection offers an array of solutions to enhance your home office and keep the same modern farmhouse style throughout the home. Upgrade your workspace with a matching computer desk and bookcase or outfit your entire home with Key West's coordinating entryway, living room, and bathroom furniture (sold separately).", NULL, NULL, NULL, NULL, NULL, 328.99, 'Furniture', '/public/images/products/furniture/img4.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03'),
(28, 'DEVAISE 3 Drawer Mobile File Cabinet', 'DEVAISE 3 Drawer Mobile File Cabinet, Wood Lateral Filing Cabinet, Printer Stand with Open Shelves for Home Office, Rustic Brown', "HEAVY DUTY & EASY ASSEMBLE: This solid constructed office lateral cabinet with evenly distributed maximum weight capacity of 150lbs. Overall dimension: 31.3'W x 15.7'D x 24.7'H (including casters), easy assembly with tools and instruction included. If you have quality problems, just contact us.
AMPLE WORKSPACE: Spacious desktop can hold your printer or scanner, while open storage shelf can easily isolate the space according to your usage.
3 DRAWERS & LARGE OPEN STORAGE: 2 top small drawers provide plenty of storage space for small items. Bottom drawer keeps hanging letter, A4 size files organized and extends fully for easy access.
EASY TO MOVE: Rolling on four wheels, this printer stand can be moved and adjusted in position freely. Built-in brakes on front two casters to keep it in position and add stability.
HEAVY DUTY & EASY ASSEMBLE: This solid constructed office lateral cabinet with evenly distributed maximum weight capacity of 150lbs. Overall dimension: 31.3'W x 15.7'D x 24.7'H (including casters), easy assembly with tools and instruction included. If you have quality problems, just contact us.", NULL, NULL, NULL, NULL, NULL, 330.99, 'Furniture', '/public/images/products/furniture/img5.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03'),
(33, 'Adjustable Office Computer Desk Chair', 'Cooked to perfection.Amazon Basics Classic Puresoft PU Padded Mid-Back Height Adjustable Office Computer Desk Chair with Armrest', "VERSATILE USE: Office desk chair for home office, work station, or conference room
ADJUSTABLE COMFORT: Adjustable seat height, adjustable seat angle, and tilt control for customizable comfort
STURDY CONSTRUCTION:Supports up to 275 pounds; sturdy KD metal base; comply with BIFMA standard, a nonprofit organization that creates voluntary standards to support safe standards for business and institutional working environments
COMFORTABLE DESIGN:Puresoft PU upholstery in Black; contoured padded seat, backrest, and armrests for comfort; durable caster wheels for smooth-rolling mobility
EASY ASSEMBLY:Assembly instructions included; components (casters, base, arms, seat mechanism, hardware kit) arrive packed in the back cushion
PRODUCT SPECIFICATIONS: Product Dimensions: 23.75 x 26 x 38.25 - 42 inches (WxDxH); seat width: 19.5 inches; seat depth: 17.75 inches; arm height: 26.25 - 30 inches", NULL, NULL, NULL, NULL, NULL, 350.99, 'Furniture', '/public/images/products/furniture/img6.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03'),
(31, 'Mobile File Cabinet, Rustic Brown', 'DEVAISE 3 Drawer Mobile File Cabinet, Wood Lateral Filing Cabinet, Printer Stand with Open Shelves for Home Office, Rustic Brown', "HEAVY DUTY & EASY ASSEMBLE: This solid constructed office lateral cabinet with evenly distributed maximum weight capacity of 150lbs. Overall dimension: 31.3'W x 15.7'D x 24.7'H (including casters), easy assembly with tools and instruction included. If you have quality problems, just contact us.
AMPLE WORKSPACE: Spacious desktop can hold your printer or scanner, while open storage shelf can easily isolate the space according to your usage.
3 DRAWERS & LARGE OPEN STORAGE: 2 top small drawers provide plenty of storage space for small items. Bottom drawer keeps hanging letter, A4 size files organized and extends fully for easy access.
EASY TO MOVE: Rolling on four wheels, this printer stand can be moved and adjusted in position freely. Built-in brakes on front two casters to keep it in position and add stability.
HEAVY DUTY & EASY ASSEMBLE: This solid constructed office lateral cabinet with evenly distributed maximum weight capacity of 150lbs. Overall dimension: 31.3'W x 15.7'D x 24.7'H (including casters), easy assembly with tools and instruction included. If you have quality problems, just contact us.", NULL, NULL, NULL, NULL, NULL, 390.99, 'Furniture', '/public/images/products/furniture/img7.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03'),
(32, 'File Cabinet', 'Bush Furniture Key West Lateral File Cabinet, Modern Farmhouse 2 Drawer File Cabinet for Home Office', "MODERN FARMHOUSE STYLE: Drawers with unique X pattern accents, a sturdy post leg design, and your choice of several slightly distressed finish options give this farmhouse filing cabinet a look that works well in homes with casual style. The Key West Collection's easy-going charm is a perfect way to convey a relaxed coastal vibe in any living space.
HOME OFFICE STORAGE: Enjoy a clutter-free workspace with paperwork that's always organized and accessible so you can access important files instantly. Each of the lateral filing cabinet's drawers can hold letter, legal, and A4-size documents weighing up to 50 pounds. Drawers open on smooth full-extension ball bearing slides for an effortless reach to contents.
COORDINATED DESIGN: The height of the 2 Drawer File Cabinet matches that of coordinating Key West Desks (sold separately) for the option to create an extended work surface when placed side-by-side. Take advantage of the extra space to keep your primary desktop clear while any documents you may need stay within arm's reach so you can access them quickly and easily.
FAMILY-FRIENDLY SAFETY: The Lateral File Cabinet's Open Safe Drawers are designed to extend one at a time for maximum stability on both hard and carpeted surfaces. Along with its stable design, the filing cabinet for home office also includes wall attachment hardware for family-friendly safety and stability in any workspace or living space.
COHESIVE LOOK: The Key West Collection offers an array of solutions to enhance your home office and keep the same modern farmhouse style throughout the home. Upgrade your workspace with a matching computer desk and bookcase or outfit your entire home with Key West's coordinating entryway, living room, and bathroom furniture (sold separately).", NULL, NULL, NULL, NULL, NULL, 130.99, 'Furniture', '/public/images/products/furniture/img8.png', TRUE,  '2024-08-27 11:24:03',  '2024-08-27 11:24:03');